name: On PR

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on:
      - self-hosted

    steps:
      - run: echo "${{ toJson(github.event) }}"

      # - uses: actions/checkout@v3

      # - name: Build image
      #   run: docker build -t songmatrix-sync-server .
