name: On push to master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: public.ecr.aws/axatol/songmatrix/sync-service

  # TODO
  # deploy
